#define CMD_TEX 1
#define CMD_LATEX 2
#define CMD_SLITEX 3
#define CMD_BIBTEX 4
#define CMD_LATEXE 5
#define CMD_AMSTEX 6
#define CMD_AMSLATEX 7
#define CMD_LYX 8

void CmdCedillaChar(int code);
void CmdUmlauteChar(int code);
void CmdGraveChar(int code);
void CmdAcuteChar(int code);
void CmdDoubleAcuteChar(int code);
void CmdTildeChar(int code);
void CmdUnderdotChar(int code);
void CmdCaronChar(int code);
void CmdRingChar(int code);
void CmdHatChar(int code);
void CmdMacronChar(int code);
void CmdVecChar(int code);
void CmdBreveChar(int code);
void CmdWideBreveChar(int code);
void CmdDotChar(int code);
void CmdUnderbarChar(int code);
void CmdDotlessChar(int code);
void CmdSymbol(int code);
void CmdUnicodeChar(int code);

void CmdLogo(int code);

void CmdFrenchAbbrev(int code);
void CmdCzechAbbrev(int code);
void CmdLatin2Char(int code);
void CmdEuro(int code);
void CmdDegreeCelsius(int code);
void CmdNot(int code);

#define IERF 1
#define IEREF 2
#define IERSF 3
#define IERESF 4
#define IEMEF 5
#define IEMESF 6
#define DEGREE 7
#define NUMERO 8
#define NUMEROS 9
#define CNUMERO 10
#define CNUMEROS 11
#define PRIMO 12
#define SECUNDO 13
#define TERTIO 14
#define QUARTO 15
#define FUP 16

#define INFERIEURA   17
#define SUPERIEURA   18
#define FRENCH_LQ    19
#define FRENCH_RQ    20
#define FRENCH_LQQ   21
#define FRENCH_RQQ   22
#define POINT_VIRGULE    23
#define POINT_EXCLAMATION    24
#define POINT_INTERROGATION  25
#define DITTO_MARK   26
#define DEUX_POINTS  27
#define LCS  28
#define FCS  29
#define FRENCH_OG 30
#define FRENCH_FG 31

#define MTEXTRA_TRIANGLELEFT   60
#define MTEXTRA_TRIANGLERIGHT  62
#define MTEXTRA_COPROD         67
#define MTEXTRA_MHO            74
#define MTEXTRA_CDOTS          76
#define MTEXTRA_VDOTS          77
#define MTEXTRA_DDOTS          79

#define MTEXTRA_NEARROW        90
#define MTEXTRA_SWARROW        91
#define MTEXTRA_SEARROW        93
#define MTEXTRA_NWARROW        94

#define MTEXTRA_MAPSTO         97
#define MTEXTRA_UPDOWNARROW    98
#define MTEXTRA_HBAR          104
#define MTEXTRA_ELL           108
#define MTEXTRA_MP            109
#define MTEXTRA_SUCC          102
#define MTEXTRA_PREC          112

#define MTEXTRA_SIMEQ             59
#define MTEXTRA_LL                61
#define MTEXTRA_GG                63
#define MTEXTRA_DOTEQ             66
#define MTEXTRA_BECAUSE           81
#define MTEXTRA_MEASUREDANGLE     82
#define MTEXTRA_DOUBLEUPDOWNARROW 99
#define MTEXTRA_RIGHTLEFTARROWS   196
#define MTEXTRA_RIGHTLEFTHARPOONS 201
#define MTEXTRA_RIGHTHARPOONUP    220
#define MTEXTRA_LEFTHARPOONDOWN   225
