#ifndef _ENCODINGS_INCLUDED
#define _ENCODINGS_INCLUDED 1

enum { 
    ENCODING_CMR = 1,
    ENCODING_CMTT,
    ENCODING_437,
    ENCODING_850,
    ENCODING_852,
    ENCODING_855,
    ENCODING_857,
    ENCODING_865,
    ENCODING_866,
    ENCODING_1250,
    ENCODING_1251,
    ENCODING_1252,
    ENCODING_1253,
    ENCODING_APPLE,
    ENCODING_APPLE_CE,
    ENCODING_APPLE_CYRILLIC,
    ENCODING_DEC,
    ENCODING_KOI8_R,
    ENCODING_KOI8_U,
    ENCODING_LATIN_2,
    ENCODING_LATIN_3,
    ENCODING_LATIN_4,
    ENCODING_LATIN_5,
    ENCODING_LATIN_9,
    ENCODING_LATIN_10,
    ENCODING_NEXT,
    ENCODING_OT2,
    ENCODING_RAW,
    ENCODING_T2A,
    ENCODING_T2B,
    ENCODING_UTF8
};


void CmdOT2Transliteration(int cThis);
void CmdChar(int code);
void WriteEightBitChar(unsigned char cThis, FILE *f);

#endif
