#!/bin/sh
# This version uses latex and dvips
#              with ghostscript
#              and  pnmcrop and pnmtopng
#
help()
{
    cat <<HELP
latex2png -- convert latex file to PNG image

USAGE: latex2png [-d density] [-h] [-k] latex_file

OPTIONS: -d density in pixels per inch
         -h help text
         -k keep intermediate files

EXAMPLE: latex2png -d 144 eqn

HELP
    exit 0
}

opt_d=144
opt_k=0
while [ -n "$1" ]; do
case $1 in
    -h) help;shift 1;;
    -k) opt_k=1;shift 1;; # variable opt_f is set
    -d) opt_d=$2;shift 2;; # -d takes an argument -> shift by 2
    --) break;;
    -*) echo "error: no such option $1. -h for help";exit 1;;
    *)  break;;
esac
done

# input check:
if [ -z "$1" ] ; then
 error "ERROR: you must specify a file, use -h for help"
 exit 1
fi

#process 'latex2png file.tex' and 'latex2png file' equivalently
name=`basename "$1" ".tex"`
dir=`dirname "$1"`

(
cd $dir
latex  --interaction batchmode $name > /dev/null
dvips -E -o $name.eps $name.dvi >& /dev/null
gs -dNOPAUSE -sDEVICE=pbmraw -r${opt_d} -sOutputFile=$name.pbm $name.eps -c quit.ps >& /dev/null
pnmcrop $name.pbm | pnmtopng > $name.png 2> /dev/null
 
if [ $opt_k -eq 0 ] ; then
	rm -f $name.dvi
	rm -f $name.aux
	rm -f $name.log
	rm -f $name.eps
	rm -f $name.pbm
fi

exit 0
)
