#!/bin/sh
# This version uses latex and dvips
#              with convert (Part of ImageMagick)
#
help()
{
    cat <<HELP
tex2png -- convert latex file to PNG image

USAGE: tex2png [-d density] [-h] [-k] latex_file

OPTIONS: -d density in pixels per inch
         -h help text
         -k keep intermediate files

EXAMPLE: tex2png -d 144 eqn

HELP
    exit 0
}

opt_d=144
opt_k=0
while [ -n "$1" ]; do
case $1 in
    -h) help;shift 1;;
    -k) opt_k=1;shift 1;; # variable opt_f is set
    -d) opt_d=$2;shift 2;; # -d takes an argument -> shift by 2
    --) break;;
    -*) echo "error: no such option $1. -h for help";exit 1;;
    *)  break;;
esac
done

# input check:
if [ -z "$1" ] ; then
 error "ERROR: you must specify a file, use -h for help"
 exit 1
fi

#process 'tex2png file.tex' and 'tex2png file' equivalently
name=`basename "$1" ".tex"`

latex  --interaction batchmode $name > /dev/null
dvips -E -o $name.eps $name.dvi >& /dev/null
convert -crop 0x0 -density ${opt_d}x${opt_d} $name.eps $name.png
if [ $opt_k -eq 0 ] ; then
	rm -f $name.dvi
	rm -f $name.aux
	rm -f $name.log
	rm -f $name.eps
fi

exit 0
