#!/bin/sh
# Part of latex2rtf by Scott Prahl (Nov 2002)
#
# This version uses latex and dvips
#              with ghostscript
#              and  pnmcrop and pnmtopng
#

DVIPS="dvips -E -R"
GHOSTSCRIPT="gs -dQUIET -dNOPAUSE -dBATCH -dSAFER"
LATEX="latex --interaction batchmode"
PNMCROP="pnmcrop"
PNMTOPNG="pnmtopng"
TEXINPSEP=":"

help()
{
    cat <<HELP
latex2png -- convert latex file to PNG image

USAGE: latex2png [-d density] [-h] [-k] [-c] [-g] [-m] [-H home dir] latex_file

OPTIONS: 
         -c color image
         -g gray image  
         -m monochrome  (default)

         -d density     (default 144 dpi)
         -h help        (default '.')
         -H /home/dir   directory to be included in search path
         -i             used to locate baseline of equations
         -k             keep intermediate files (for debugging)

EXAMPLE: 
         latex2png -d 144 /tmp/file   #create /tmp/file.png at 144 dpi
         latex2png -H . /tmp/file     #search the cwd for image files

HELP
    exit 0
}

opt_d=144
opt_i=0
opt_k=0
home_dir="."
device="b"                      #black & white
ext="pbm"
output="pbmraw"

while [ -n "$1" ]; do
case $1 in
    -g) ext="pgm";  output="pgmraw"; shift 1;; #gray
    -c) ext="ppm";  output="ppmraw";  shift 1;; #color
    -m) ext="pbm";  output="pbmraw"; shift 1;; #monochrome
    -h) help;        shift 1;;
    -i) opt_i=1;     shift 1;;
    -k) opt_k=1;     shift 1;; 
    -d) opt_d=$2;    shift 2;; #shift by 2 due to argument
    -H) home_dir=$2; shift 2;;
    --) break;;
    -*) echo "error:no such option $1"; exit 1;;
    *)  break;;
esac
done

# input check:
if [ -z "$1" ] ; then
 echo "error: no latex_file specified"
 exit 1
fi

#process 'latex2png file.tex' and 'latex2png file' equivalently
name=`basename "$1" ".tex"`
dir=`dirname "$1"`

#add $home_dir to latex/dvips search path
cd $home_dir
TEXINPUTS=`pwd`${TEXINPSEP}
export TEXINPUTS
cd $dir

$LATEX $name > /dev/null

if [ ! -e "$name.dvi" ] ; then
    echo "error: latex failed to translate $name.tex to $name.dvi"
    exit 1
fi

$DVIPS -o $name.ps $name.dvi >& /dev/null

if [ ! -e "$name.ps" ] ; then
    echo "error: dvips failed to translate $name.dvi to $name.ps"
    exit 1
fi

$GHOSTSCRIPT -sDEVICE=${output} -r${opt_d} -sOutputFile=$name.$ext $name.ps >& /dev/null

if [ ! -e "$name.$ext" ] ; then
    echo "error: ghostscript failed to translate $name.ps to $name.$ext"
    exit 1
fi

$PNMCROP $name.$ext | $PNMTOPNG > $name.png 2> /dev/null

if [ ! -e "$name.png" ] ; then
    echo "error: pnmcrop or pnmtopng failed to crop and translate $name.$ext to $name.png"
    exit 1
fi

if [ $opt_k -eq 0 ] ; then
    rm -f $name.dvi
    rm -f $name.aux
    rm -f $name.log
    rm -f $name.ps
    rm -f $name.$ext
fi

exit 0

