#!/bin/sh
# Part of latex2rtf by Scott Prahl (Nov 2002)
#
# This version uses pdflatex
#              and  pstoimg that comes with latex2html
#
# this version does not work with included eps graphics unless pdflatex has
# supports the eps graphic format.  Works fine for for including equations.
#

PDFLATEX="pdflatex --interaction batchmode"
PSTOIMG="pstoimg"
TEXINPSEP=":"

help()
{
    cat <<HELP
latex2png -- convert latex file to PNG image

USAGE: latex2png [-d density] [-h] [-k] [-c] [-g] [-m] [-H home dir] latex_file

OPTIONS: 
         -c color image
         -g gray image  
         -m monochrome  (default)

         -d density     (default 144 dpi)
         -h help        (default '.')
         -H /home/dir   directory to be included in search path
         -i             used to locate baseline of equations
         -k             keep intermediate files (for debugging)

EXAMPLE: 
         latex2png -d 144 /tmp/file   #create /tmp/file.png at 144 dpi
         latex2png -H . /tmp/file     #search the cwd for image files

HELP
    exit 0
}

opt_d=144
opt_i=0
opt_k=0
home_dir="."
device="1"                      #black & white

while [ -n "$1" ]; do
case $1 in
    -g) device="8";  shift 1;; #gray
    -c) device="24"; shift 1;; #color
    -m) device="1";  shift 1;; #monochrome
    -h) help;        shift 1;;
    -i) opt_i=1;     shift 1;;
    -k) opt_k=1;     shift 1;; 
    -d) opt_d=$2;    shift 2;; #shift by 2 due to argument
    -H) home_dir=$2; shift 2;;
    --) break;;
    -*) echo "error:no such option $1"; exit 1;;
    *)  break;;
esac
done

# input check:
if [ -z "$1" ] ; then
 echo "no latex_file specified"
 exit 1
fi

#process 'latex2png file.tex' and 'latex2png file' equivalently
name=`basename "$1" ".tex"`
dir=`dirname "$1"`

#need to search the current working directory for \input or \include
cd $home_dir
TEXINPUTS=`pwd`${TEXINPSEP}
export TEXINPUTS
cd $dir

$PDFLATEX $name > /dev/null

if [ ! -e "$name.pdf" ] ; then
    echo "error: pdflatex failed to translate $name.tex to $name.pdf"
    exit 1
fi

$PSTOIMG -crop lbtr -color ${device} -density ${opt_d} -type png $name.pdf >& /dev/null

if [ ! -e "$name.png" ] ; then
    echo "error: pstoimg (from latex2html) failed to translate $name.pdf to $name.png"
    exit 1
fi

if [ $opt_k -eq 0 ] ; then
    rm -f $name.aux
    rm -f $name.log
    rm -f $name.pdf
fi
