#!/bin/sh
if [ -z "$1" ] ; then
    error "no input file specified"
    exit 1
fi

if [ -z $3 ] ; then 
    dpi=300;
else
    dpi=$3
fi

exec /usr/bin/sips -s format png -s dpiHeight $dpi -s dpiWidth $dpi --out $2 $1
