#!/bin/sh
if [ -z "$1" ] ; then
    error "no input file specified"
    exit 1
fi

if [ -z $3 ] ; then 
    dpi=300;
else
    dpi=$3
fi

gs -q -dNOPAUSE -dBATCH -dSAFER -sDEVICE=pngalpha -r$dpi -sOutputFile=$2 $1
